version: '3'

services:
  # PresentationTier 
  front-n1:
    build: ./PresentationTier/Website/
    ports:
      - "81:80"
    networks:
      - app-network
  front-n2:
    build: ./PresentationTier/Website/
    ports:
      - "82:80"
    networks:
      - app-network
  front-n3:
    build: ./PresentationTier/Website/
    ports:
      - "83:80"
    networks:
      - app-network
  front-loadbalancer:
    build: ./PresentationTier/LoadBalancer/
    ports:
      - "80:80"
    depends_on:
      - front-n1
      - front-n2
      - front-n3
    networks:
      - app-network

  # BusinessTier
  back-n1:
    build: ./BusinessTier/Backend/
    ports:
      - "85:80"
    networks:
      - app-network
  back-n2:
    build: ./BusinessTier/Backend/
    ports:
      - "86:80"
    networks:
      - app-network
  back-n3:
    build: ./BusinessTier/Backend/
    ports:
      - "88:80"
    networks:
      - app-network
  back-loadbalancer:
    build: ./BusinessTier/LoadBalancer/
    ports:
      - "84:84"
    depends_on:
      - back-n1
      - back-n2
      - back-n3
    networks:
      - app-network

  # DataTier
  data-mongo1:
    image: mongo:6.0.4
    container_name: data-mongo1
    ports:
      - "40001:27017"
    networks:
      - app-network
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
  data-mongo2:
    image: mongo:6.0.4
    container_name: data-mongo2
    ports:
      - "40002:27017"
    networks:
      - app-network
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
  data-mongo3:
    image: mongo:6.0.4
    container_name: data-mongo3
    ports:
      - "40003:27017"
    networks:
      - app-network
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
  mongo-config:
    image: mongo:6.0.4
    hostname: Mongo-config
    container_name: Mongo-config
    networks:
      - app-network
    depends_on:
      - data-mongo1
      - data-mongo2
      - data-mongo3
    restart: "no"
    volumes:
      - ./database/setup.sh:/database/setup.sh
      - ./database/init.js:/database/init.js
    entrypoint: [ "bash", "/database/setup.sh" ]

networks:
  app-network:
    name: app-network